name: summer_school_microbiome
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython=1.79
  - bowtie2=2.4.4
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - jupyter_server=1.10.2
  - jupyterlab=3.1.4
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.6.2
  - kiwisolver=1.3.1
  - mash=2.3
  - metaphlan=3.0.13
  - nb_conda=2.2.1
  - nb_conda_kernels=2.3.1
  - numpy=1.21.1
  - plotnine=0.8.0
  - phylophlan=3.0.2
  - pysam=0.16.0.1
  - python=3.9.6
  - samtools=1.13
  - scikit-bio=0.5.6
  - scikit-learn=0.24.2
  - scipy=1.7.1
  - seaborn=0.11.1
  - seaborn-base=0.11.1
  - setuptools=52.0.0
  - sqlite=3.36.0
  - statsmodels=0.12.2
